#ifndef ZY_ROS_CONNECTOR_INIT_H
#define ZY_ROS_CONNECTOR_INIT_H

#include <sofa/helper/system/config.h>

#ifdef SOFA_BUILD_ZY_ROS_CONNECTOR
#  define SOFA_ZY_ROS_CONNECTOR_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_ZY_ROS_CONNECTOR_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#endif // ZY_ROS_CONNECTOR_INIT_H
