#ifndef ZY_VELOCITY_APPROXIMATION_HANDLER_CONFIG_H
#define ZY_VELOCITY_APPROXIMATION_HANDLER_CONFIG_H

#include <sofa/helper/system/config.h>

#ifdef SOFA_BUILD_ZY_VELOCITY_APPROXIMATION_HANDLER
#  define SOFA_ZY_VELOCITY_APPROXIMATION_HANDLER_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_ZY_VELOCITY_APPROXIMATION_HANDLER_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#endif // ZY_VELOCITY_APPROXIMATION_HANDLER_CONFIG_H
