#ifndef SOFA_ZY_ROS_SUBSCRIPTIONHELPER_CONFIG_H
#define SOFA_ZY_ROS_SUBSCRIPTIONHELPER_CONFIG_H

#include <sofa/helper/system/config.h>

#ifdef SOFA_BUILD_ZY_ROS_SUBSCRIPTIONHELPER
#  define SOFA_ZY_ROS_SUBSCRIPTIONHELPER_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_ZY_ROS_SUBSCRIPTIONHELPER_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#endif // SOFA_ZY_ROS_SUBSCRIPTIONHELPER_CONFIG_H
