#ifndef ZY_SOFA_GRIPPINGHANDLER_CONFIG_H
#define ZY_SOFA_GRIPPINGHANDLER_CONFIG_H

#include <sofa/helper/system/config.h>

#ifdef BUILD_ZY_SOFA_GRIPPINGHANDLER
#  define ZY_SOFA_GRIPPINGHANDLER_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define ZY_SOFA_GRIPPINGHANDLER_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#endif // ZY_SOFA_GRIPPINGHANDLER_CONFIG_H
