#ifndef TRU_SOFA_GRIPPINGHANDLER_CONFIG_H
#define TRU_SOFA_GRIPPINGHANDLER_CONFIG_H

#include <sofa/helper/system/config.h>

#ifdef BUILD_TRU_SOFA_GRIPPINGHANDLER
#  define TRU_SOFA_GRIPPINGHANDLER_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define TRU_SOFA_GRIPPINGHANDLER_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#endif // TRU_SOFA_GRIPPINGHANDLER_CONFIG_H