#ifndef SOFA_ZY_ROS_PUBLISHINGHANDLER_CONFIG_H
#define SOFA_ZY_ROS_PUBLISHINGHANDLER_CONFIG_H

#include <sofa/helper/system/config.h>

#ifdef BUILD_SOFA_ZY_ROS_PUBLISHINGHANDLER
#  define SOFA_ZY_ROS_PUBLISHINGHANDLER_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_ZY_ROS_PUBLISHINGHANDLER_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#endif //SOFA_ZY_ROS_PUBLISHINGHANDLER_CONFIG_H
