#ifndef TRU_MULTITHREADING_CONFIG_H
#define TRU_MULTITHREADING_CONFIG_H

#include <sofa/helper/system/config.h>

#ifdef BUILD_TRU_MULTITHREADING
#  define TRU_MULTITHREADING_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define TRU_MULTITHREADING_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#endif //TRU_MULTITHREADING_CONFIG_H