// Generated by gencpp from file zyrosconnector_test/ArrayOfFloatsResponse.msg
// DO NOT EDIT!


#ifndef ZYROSCONNECTOR_TEST_MESSAGE_ARRAYOFFLOATSRESPONSE_H
#define ZYROSCONNECTOR_TEST_MESSAGE_ARRAYOFFLOATSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32MultiArray.h>

namespace zyrosconnector_test
{
template <class ContainerAllocator>
struct ArrayOfFloatsResponse_
{
  typedef ArrayOfFloatsResponse_<ContainerAllocator> Type;

  ArrayOfFloatsResponse_()
    : return_values()  {
    }
  ArrayOfFloatsResponse_(const ContainerAllocator& _alloc)
    : return_values(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _return_values_type;
  _return_values_type return_values;





  typedef boost::shared_ptr< ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ArrayOfFloatsResponse_

typedef ::zyrosconnector_test::ArrayOfFloatsResponse_<std::allocator<void> > ArrayOfFloatsResponse;

typedef boost::shared_ptr< ::zyrosconnector_test::ArrayOfFloatsResponse > ArrayOfFloatsResponsePtr;
typedef boost::shared_ptr< ::zyrosconnector_test::ArrayOfFloatsResponse const> ArrayOfFloatsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace zyrosconnector_test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/alpenland/data/acer-aspire/volume1/src/melodic/install_isolated/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea1cfc45e2a9d8be6c357870ab2ea4aa";
  }

  static const char* value(const ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea1cfc45e2a9d8beULL;
  static const uint64_t static_value2 = 0x6c357870ab2ea4aaULL;
};

template<class ContainerAllocator>
struct DataType< ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zyrosconnector_test/ArrayOfFloatsResponse";
  }

  static const char* value(const ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32MultiArray return_values\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float32[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.return_values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArrayOfFloatsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zyrosconnector_test::ArrayOfFloatsResponse_<ContainerAllocator>& v)
  {
    s << indent << "return_values: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.return_values);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZYROSCONNECTOR_TEST_MESSAGE_ARRAYOFFLOATSRESPONSE_H
