// Generated by gencpp from file zyrosconnector_test/ArrayOfFloatsRequest.msg
// DO NOT EDIT!


#ifndef ZYROSCONNECTOR_TEST_MESSAGE_ARRAYOFFLOATSREQUEST_H
#define ZYROSCONNECTOR_TEST_MESSAGE_ARRAYOFFLOATSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int32.h>

namespace zyrosconnector_test
{
template <class ContainerAllocator>
struct ArrayOfFloatsRequest_
{
  typedef ArrayOfFloatsRequest_<ContainerAllocator> Type;

  ArrayOfFloatsRequest_()
    : FloatsToReturn()  {
    }
  ArrayOfFloatsRequest_(const ContainerAllocator& _alloc)
    : FloatsToReturn(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int32_<ContainerAllocator>  _FloatsToReturn_type;
  _FloatsToReturn_type FloatsToReturn;





  typedef boost::shared_ptr< ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ArrayOfFloatsRequest_

typedef ::zyrosconnector_test::ArrayOfFloatsRequest_<std::allocator<void> > ArrayOfFloatsRequest;

typedef boost::shared_ptr< ::zyrosconnector_test::ArrayOfFloatsRequest > ArrayOfFloatsRequestPtr;
typedef boost::shared_ptr< ::zyrosconnector_test::ArrayOfFloatsRequest const> ArrayOfFloatsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace zyrosconnector_test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/alpenland/data/acer-aspire/volume1/src/melodic/install_isolated/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99e884397895104c5976ee3b5ba9316a";
  }

  static const char* value(const ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99e884397895104cULL;
  static const uint64_t static_value2 = 0x5976ee3b5ba9316aULL;
};

template<class ContainerAllocator>
struct DataType< ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zyrosconnector_test/ArrayOfFloatsRequest";
  }

  static const char* value(const ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int32 FloatsToReturn\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int32\n"
"int32 data\n"
;
  }

  static const char* value(const ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.FloatsToReturn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArrayOfFloatsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zyrosconnector_test::ArrayOfFloatsRequest_<ContainerAllocator>& v)
  {
    s << indent << "FloatsToReturn: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.FloatsToReturn);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZYROSCONNECTOR_TEST_MESSAGE_ARRAYOFFLOATSREQUEST_H
